const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'../public'); const output=process.env.HANDY_TEST_OUTPUT||path.join(require('os').tmpdir(),'medienblick-workshop-check');fs.mkdirSync(output,{recursive:true});
(async()=>{
const browser=await chromium.launch({headless:true,...(process.env.HANDY_CHROME?{executablePath:process.env.HANDY_CHROME}:{})});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://demo.local/**',async route=>{const url=new URL(route.request().url()),pathname=url.pathname;
 if(pathname==='/')return route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="de"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/app.css"></head><body><main id="main" tabindex="-1"></main><div id="notice"></div></body></html>'});
 const file=path.join(root,pathname);if(!fs.existsSync(file))return route.fulfill({status:404});const ext=path.extname(file);const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.webp':'image/webp','.pdf':'application/pdf'};
return route.fulfill({contentType:types[ext]||'text/plain',body:fs.readFileSync(file)});});
await page.goto('http://demo.local/?view=projects');await page.addScriptTag({path:path.join(root,'assets/project-data.js')});await page.addScriptTag({content:fs.readFileSync(path.join(root,'assets/app.js'),'utf8').replace(/init\(\);\s*$/,'')});await page.evaluate(()=>projectPage());
for(const width of [1440,390]){
 await page.setViewportSize({width,height:1000});await page.locator('[data-workshop="general"]').click();assert.equal(await page.locator('.workshop-card').count(),4);
 await page.locator('.workshop-card').nth(2).locator('summary').first().click();assert.equal(await page.locator('.reflection-plan details').count(),7);await page.locator('.workshop-card').nth(2).locator('summary').first().click();
 await page.screenshot({path:path.join(output,'workshop-general-'+width+'.png'),fullPage:true});
 await page.locator('[data-workshop="subject"]').click();assert.equal(await page.locator('.workshop-card').count(),17);await page.selectOption('#workshop-subject','Sport');assert.equal(await page.locator('.workshop-card').count(),1);assert.match(await page.locator('.workshop-card h3').textContent(),/Bewegung/);
 await page.selectOption('#workshop-subject','');await page.fill('#workshop-search','Physik');assert.equal(await page.locator('.workshop-card').count(),2);await page.fill('#workshop-search','unbekanntesfachzz');assert.equal(await page.locator('.workshop-card').count(),0);await page.fill('#workshop-search','');
 await page.screenshot({path:path.join(output,'workshop-subject-'+width+'.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('[data-workshop="school"]').click();assert.equal(await page.locator('.framework-card').count(),6);await page.locator('.framework-card summary').first().click();assert.equal(await page.locator('.framework-card[open]').count(),1);await page.screenshot({path:path.join(output,'workshop-school-'+width+'.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('[data-workshop="school"]').focus();await page.keyboard.press('Home');assert.equal(await page.locator('[data-workshop="general"]').getAttribute('aria-selected'),'true');await page.keyboard.press('ArrowRight');assert.equal(await page.locator('[data-workshop="subject"]').getAttribute('aria-selected'),'true');
}
const ids=await page.evaluate(()=>projectLibrary.map(p=>p.id));
for(const id of ids){await page.goto('http://demo.local/assets/material/projektprotokoll.html?project='+id);await page.waitForFunction(()=>document.querySelector('#project-title').value.length>0);assert(await page.locator('#question').inputValue());assert.equal(await page.locator('#project-brief').getAttribute('hidden'),null);assert.equal(await page.locator('form textarea').count(),16);}
await page.goto('http://demo.local/assets/material/projektprotokoll.html?project=sport');await page.fill('#result','Wir haben zwei Bewegungsphasen verglichen. <img src=x onerror=alert(1)> bleibt Text.');
await page.evaluate(()=>sheetPrintValues());assert.match(await page.locator('#result + .print-value').textContent(),/bleibt Text/);assert.equal(await page.locator('#result + .print-value img').count(),0);
await page.setViewportSize({width:390,height:1000});await page.screenshot({path:path.join(output,'protocol-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.pdf({path:path.join(output,'protocol-print.pdf'),format:'A4',printBackground:true});
const downloadEvent=page.waitForEvent('download');await page.locator('#sheet-export').click();const downloaded=await downloadEvent;assert.equal(downloaded.suggestedFilename(),'medienblick-project-entwurf.json'); const exported=await page.evaluate(()=>({format:'medienblick-project',version:1,project:'sport',values:Object.fromEntries([...document.querySelectorAll('form input[name],form textarea[name]')].map(f=>[f.name,f.value]))}));
page.on('dialog',d=>d.accept());await page.fill('#result','changed');await page.locator('#sheet-import').setInputFiles({name:'entwurf.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await page.waitForFunction(()=>document.querySelector('#sheet-status').textContent.includes('geöffnet'));assert.match(await page.locator('#result').inputValue(),/Bewegungsphasen/);
await page.locator('#sheet-import').setInputFiles({name:'wrong.json',mimeType:'application/json',buffer:Buffer.from('{"format":"wrong"}')});await page.waitForFunction(()=>document.querySelector('#sheet-status').textContent.includes('passt nicht'));assert.match(await page.locator('#result').inputValue(),/Bewegungsphasen/);
await page.goto('http://demo.local/assets/material/projektprotokoll.html?project=unknown');assert.match(await page.locator('#sheet-status').textContent(),/unbekannt/);
await page.goto('http://demo.local/assets/material/schulkonzept.html');assert.equal(await page.locator('form textarea').count(),11);await page.fill('#school-goals','Ein begrenzter Pilot mit zwei Partnerfächern.');await page.evaluate(()=>sheetPrintValues());await page.pdf({path:path.join(output,'school-print.pdf'),format:'A4',printBackground:true});await page.screenshot({path:path.join(output,'school-form-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: three areas desktop/mobile, subject/search filters, keyboard tabs, 21 linked briefs, local draft import, safe text rendering, print protocol and school plan, no overflow or runtime errors.');
})().catch(e=>{console.error(e);process.exit(1)});
